server:
    port: 8080
    error:
        include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: anthual
    password: anthual
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true